"""remove primarykey2

Revision ID: 020f64851c2b
Revises: 537907610f74
Create Date: 2023-08-03 13:58:45.078721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020f64851c2b'
down_revision = '537907610f74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
