"""changed users to user2

Revision ID: 07a46f5dce87
Revises: a851c58d7c97
Create Date: 2023-08-03 10:42:36.960658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a46f5dce87'
down_revision = 'a851c58d7c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
