"""changed users to user2

Revision ID: 2a759591cc80
Revises: 07a46f5dce87
Create Date: 2023-08-03 10:54:04.035686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a759591cc80'
down_revision = '07a46f5dce87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
