"""remove primarykey2

Revision ID: 3ed4aef26128
Revises: 020f64851c2b
Create Date: 2023-08-03 14:00:44.242462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed4aef26128'
down_revision = '020f64851c2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
