"""changed properties2

Revision ID: 447b2c4fe08f
Revises: 2a759591cc80
Create Date: 2023-08-03 11:39:34.591151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447b2c4fe08f'
down_revision = '2a759591cc80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_game_id_games', type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_users_game_id_games', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###
