"""updated all priperties2

Revision ID: 46e06b8f7e91
Revises: a63bbec364d8
Create Date: 2023-08-03 12:05:22.149007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e06b8f7e91'
down_revision = 'a63bbec364d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
