"""remove primarykey2

Revision ID: 537907610f74
Revises: db6b593e2b7c
Create Date: 2023-08-03 13:41:39.410717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537907610f74'
down_revision = 'db6b593e2b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
