"""updated all priperties2

Revision ID: a1805a0f7701
Revises: a53f5b3dbb36
Create Date: 2023-08-03 12:21:40.079759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1805a0f7701'
down_revision = 'a53f5b3dbb36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
