"""added games 2

Revision ID: a2911730f24e
Revises: 857d5e3ff04f
Create Date: 2023-08-03 10:27:11.412129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2911730f24e'
down_revision = '857d5e3ff04f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
