"""updated all priperties2

Revision ID: a53f5b3dbb36
Revises: 46e06b8f7e91
Create Date: 2023-08-03 12:09:54.708155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53f5b3dbb36'
down_revision = '46e06b8f7e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
