"""updated all priperties2

Revision ID: a63bbec364d8
Revises: 447b2c4fe08f
Create Date: 2023-08-03 11:55:39.368567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63bbec364d8'
down_revision = '447b2c4fe08f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
