"""added games 2

Revision ID: a851c58d7c97
Revises: a2911730f24e
Create Date: 2023-08-03 10:29:33.526953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a851c58d7c97'
down_revision = 'a2911730f24e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
