"""updated all priperties2

Revision ID: a9b3d4d08df1
Revises: b3819c6828f5
Create Date: 2023-08-03 13:05:43.474139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b3d4d08df1'
down_revision = 'b3819c6828f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
