"""updated all priperties2

Revision ID: b3819c6828f5
Revises: a1805a0f7701
Create Date: 2023-08-03 12:35:08.842366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3819c6828f5'
down_revision = 'a1805a0f7701'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
