"""updated all priperties2

Revision ID: db6b593e2b7c
Revises: b33d2804517f
Create Date: 2023-08-03 13:35:17.601684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6b593e2b7c'
down_revision = 'b33d2804517f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
