"""added game_id to userstable

Revision ID: eeb15eba9a94
Revises: ed9918993f29
Create Date: 2023-08-03 09:43:02.190712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb15eba9a94'
down_revision = 'ed9918993f29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_game_id_games'), 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_game_id_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
